Fixed octet compiling on mac using make file
-octet/MakeFile
Added std=c++11 for lambda usage

-octet/src/scene/mesh.h:
cast to int32_t unsigned ints to int32_t for edge constructor

-octet/src/scene/scene_node.h
using sqrt instead of std::sqrt
(Compiler error:
“error: no member named 'sqrt' in namespace 'std'; did you mean simply
'sqrt’?”
)